
name: 2025 Go CI

on:
  push:
    paths:
      - "2025/**"
  pull_request:
    paths:
      - "2025/**"
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    working-directory: "2025"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 2025/go.mod
          cache: true

      - name: Test
        run: go test ./...
